version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: live_library_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sonne1!#
      MYSQL_DATABASE: living_library_manage_system
    ports:
      - "3307:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: live_library_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_library_ui
    command: >
      streamlit run backend/app.py
      --server.port=8051
      --server.address=0.0.0.0
    ports:
      - "8051:8051"
    env_file: .env
    depends_on:
      - backend
    volumes:
      - .:/app    #frontend




# services:
#   db:
#     image: mysql:8.0
#     container_name: live_library_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: Sonne1!#
#       MYSQL_DATABASE: living_library_manage_system
#     ports:
#       - "3307:3306" 
#     volumes:
#       - ./data:/docker-entrypoint-initdb.d

#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     container_name: live_library_backend
#     depends_on:
#       - db
#     env_file: .env
#     volumes:
#       - .:/app
#     ports:
#       - "8001:8001"

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: live_library_ui
# # new command for login page
#     command: streamlit run backend/app.py --server.port=8000 --server.address=0.0.0.0
#     ports:
#       - "8051:8051" #"8000:8000"
#     env_file: .env
#     depends_on:
#       #- db
#       - backend
#     volumes:
#       - .:/app    # frontend 

